---
# pour installer ces trucs, il faut faire la commande suivante:
# ansible-galaxy install -r requirements.yml

collections:
  # Install a collection from Ansible Galaxy.
  - name: 'amazon.aws'
    version: '6.3.0'
    source: 'https://galaxy.ansible.com'
  - name: 'community.docker'
    version: '3.4.8'
    source: 'https://galaxy.ansible.com'
  - name: 'community.general'
    version: '6.3.0'
    source: 'https://galaxy.ansible.com'
  - name: 'community.grafana'
    version: '1.5.4'
    source: 'https://galaxy.ansible.com'
  - name: 'community.mysql'
    version: '3.7.2'
    source: 'https://galaxy.ansible.com'
  - name:  'community.vmware'
    version: '3.9.0'
    source: 'https://galaxy.ansible.com'
  - name: 'devsec.hardening'
    version: '7.15.0'
    source: 'https://galaxy.ansible.com'
  